export const FALLBACK_PRICING = {
  schemaVersion: 4,
  models: [
    { id: 'claude-sonnet-5',            name: 'Claude Sonnet 5',           provider: 'Anthropic', inputPer1M: 3.00,  outputPer1M: 15.00 },
    { id: 'claude-4-sonnet',            name: 'Claude 4 Sonnet',           provider: 'Anthropic', inputPer1M: 3.00,  outputPer1M: 15.00 },
    { id: 'claude-sonnet-4-6',          name: 'Claude 4.6 Sonnet',         provider: 'Anthropic', inputPer1M: 3.00,  outputPer1M: 15.00 },
    { id: 'claude-4-5-sonnet',          name: 'Claude 4.5 Sonnet',         provider: 'Anthropic', inputPer1M: 3.00,  outputPer1M: 15.00 },
    { id: 'claude-opus-5',              name: 'Claude Opus 5',             provider: 'Anthropic', inputPer1M: 5.00,  outputPer1M: 25.00 },
    { id: 'claude-opus-4-8',            name: 'Claude Opus 4.8',           provider: 'Anthropic', inputPer1M: 5.00,  outputPer1M: 25.00 },
    { id: 'claude-fable-5-1',           name: 'Claude Fable 5.1',          provider: 'Anthropic', inputPer1M: 10.00, outputPer1M: 50.00 },
    { id: 'claude-fable-5',             name: 'Claude Fable 5',            provider: 'Anthropic', inputPer1M: 10.00, outputPer1M: 50.00 },
    { id: 'claude-opus-4-7',            name: 'Claude Opus 4.7',           provider: 'Anthropic', inputPer1M: 5.00,  outputPer1M: 25.00 },
    { id: 'claude-opus-4-7-fast',       name: 'Claude Opus 4.7 Fast',      provider: 'Anthropic', inputPer1M: 30.00, outputPer1M: 150.00 },
    { id: 'claude-4-6-opus',            name: 'Claude 4.6 Opus',           provider: 'Anthropic', inputPer1M: 5.00,  outputPer1M: 25.00 },
    { id: 'claude-4-5-opus',            name: 'Claude 4.5 Opus',           provider: 'Anthropic', inputPer1M: 5.00,  outputPer1M: 25.00 },
    { id: 'claude-4-5-haiku',           name: 'Claude 4.5 Haiku',          provider: 'Anthropic', inputPer1M: 1.00,  outputPer1M: 5.00 },
    { id: 'claude-4-sonnet-1m',         name: 'Claude 4 Sonnet 1M',        provider: 'Anthropic', inputPer1M: 6.00,  outputPer1M: 22.50 },
    { id: 'gemini-3.1-pro',             name: 'Gemini 3.1 Pro',            provider: 'Google',    inputPer1M: 2.00,  outputPer1M: 12.00 },
    { id: 'gemini-3-pro',               name: 'Gemini 3 Pro',              provider: 'Google',    inputPer1M: 2.00,  outputPer1M: 12.00 },
    { id: 'gemini-3.8-flash',           name: 'Gemini 3.8 Flash',          provider: 'Google',    inputPer1M: 0.75,  outputPer1M: 3.50 },
    { id: 'gemini-3.7-flash',           name: 'Gemini 3.7 Flash',          provider: 'Google',    inputPer1M: 0.75,  outputPer1M: 3.50 },
    { id: 'gemini-3.6-flash',           name: 'Gemini 3.6 Flash',          provider: 'Google',    inputPer1M: 1.50,  outputPer1M: 7.50 },
    { id: 'gemini-3.5-flash',           name: 'Gemini 3.5 Flash',          provider: 'Google',    inputPer1M: 1.50,  outputPer1M: 9.00 },
    { id: 'gemini-3-flash',             name: 'Gemini 3 Flash',            provider: 'Google',    inputPer1M: 0.50,  outputPer1M: 3.00 },
    { id: 'gemini-3-pro-image-preview', name: 'Gemini 3 Pro Image Preview', provider: 'Google',   inputPer1M: 2.00,  outputPer1M: 12.00 },
    { id: 'gemini-2.5-flash',           name: 'Gemini 2.5 Flash',          provider: 'Google',    inputPer1M: 0.30,  outputPer1M: 2.50 },
    { id: 'gpt-5.1',                    name: 'GPT-5.1',                   provider: 'OpenAI',    inputPer1M: 1.25,  outputPer1M: 10.00 },
    { id: 'gpt-5-codex',                name: 'GPT-5 Codex',               provider: 'OpenAI',    inputPer1M: 1.25,  outputPer1M: 10.00 },
    { id: 'gpt-5-mini',                 name: 'GPT-5 Mini',                provider: 'OpenAI',    inputPer1M: 0.25,  outputPer1M: 2.00 },
    { id: 'gpt-5-fast',                 name: 'GPT-5 Fast',                provider: 'OpenAI',    inputPer1M: 2.50,  outputPer1M: 20.00 },
    { id: 'gpt-5.2',                    name: 'GPT-5.2',                   provider: 'OpenAI',    inputPer1M: 1.75,  outputPer1M: 14.00 },
    { id: 'gpt-5.2-codex',              name: 'GPT-5.2 Codex',             provider: 'OpenAI',    inputPer1M: 1.75,  outputPer1M: 14.00 },
    { id: 'gpt-5.6-sol',                name: 'GPT-5.6 Sol',               provider: 'OpenAI',    inputPer1M: 5.00,  outputPer1M: 30.00 },
    { id: 'gpt-5.6-terra',              name: 'GPT-5.6 Terra',             provider: 'OpenAI',    inputPer1M: 2.50,  outputPer1M: 15.00 },
    { id: 'gpt-5.6-luna',               name: 'GPT-5.6 Luna',              provider: 'OpenAI',    inputPer1M: 1.00,  outputPer1M: 6.00 },
    { id: 'gpt-5.5',                    name: 'GPT-5.5',                   provider: 'OpenAI',    inputPer1M: 5.00,  outputPer1M: 30.00 },
    { id: 'gpt-5.4',                    name: 'GPT-5.4',                   provider: 'OpenAI',    inputPer1M: 2.50,  outputPer1M: 15.00 },
    { id: 'gpt-5.4-mini',               name: 'GPT-5.4 Mini',              provider: 'OpenAI',    inputPer1M: 0.75,  outputPer1M: 4.50 },
    { id: 'gpt-5.4-nano',               name: 'GPT-5.4 Nano',              provider: 'OpenAI',    inputPer1M: 0.20,  outputPer1M: 1.25 },
    { id: 'gpt-5.3-codex',              name: 'GPT-5.3 Codex',             provider: 'OpenAI',    inputPer1M: 1.75,  outputPer1M: 14.00 },
    { id: 'gpt-5.1-codex',              name: 'GPT-5.1 Codex',             provider: 'OpenAI',    inputPer1M: 1.25,  outputPer1M: 10.00 },
    { id: 'gpt-5.1-codex-mini',         name: 'GPT-5.1 Codex Mini',        provider: 'OpenAI',    inputPer1M: 0.25,  outputPer1M: 2.00 },
    { id: 'gpt-5.1-codex-max',          name: 'GPT-5.1 Codex Max',         provider: 'OpenAI',    inputPer1M: 1.25,  outputPer1M: 10.00 },
    { id: 'grok-4.6',                   name: 'Grok 4.6',                  provider: 'Cursor',    inputPer1M: 2.00,  outputPer1M: 6.00 },
    { id: 'grok-4.5',                   name: 'Grok 4.5',                  provider: 'Cursor',    inputPer1M: 2.00,  outputPer1M: 6.00 },
    { id: 'kimi-k3',                    name: 'Kimi K3',                   provider: 'Moonshot',  inputPer1M: 3.00,  outputPer1M: 15.00 },
    { id: 'kimi-k2.7-code',             name: 'Kimi K2.7 Code',            provider: 'Moonshot',  inputPer1M: 0.95,  outputPer1M: 4.00 },
    { id: 'glm-5.2',                    name: 'GLM-5.2',                   provider: 'Z.ai',      inputPer1M: 1.40,  outputPer1M: 4.40 },
    { id: 'composer-1',                 name: 'Composer 1',                provider: 'Cursor',    inputPer1M: 1.25,  outputPer1M: 10.00 },
    { id: 'composer-2.5',               name: 'Composer 2.5',              provider: 'Cursor',    inputPer1M: 0.50,  outputPer1M: 2.50 },
  ],
  lastUpdated: null,
  source: 'bundled',
  origin: 'local',
};

export const DEFAULT_SETTINGS = {
  setupComplete: false,
  selectedMonitor: 0,
  overlayPosition: 'top-right',
  opacity: 90,
  peakHours: {
    enabled: false,
    start: '09:00',
    end: '18:00',
    days: [1, 2, 3, 4, 5],
  },
  visibleModels: null,
  notifications: true,
  refreshIntervalHours: 6,
};
