export const FALLBACK_PRICING = {
  models: [
    {
      id: 'claude-3-7-sonnet-20250219',
      name: 'Claude Sonnet 3.7',
      provider: 'Anthropic',
      inputPer1M: 3.00,
      outputPer1M: 15.00,
    },
    {
      id: 'claude-3-5-sonnet-20241022',
      name: 'Claude Sonnet 3.5',
      provider: 'Anthropic',
      inputPer1M: 3.00,
      outputPer1M: 15.00,
    },
    {
      id: 'claude-opus-4-5',
      name: 'Claude Opus 4.5',
      provider: 'Anthropic',
      inputPer1M: 15.00,
      outputPer1M: 75.00,
    },
    {
      id: 'claude-3-opus-20240229',
      name: 'Claude Opus 3',
      provider: 'Anthropic',
      inputPer1M: 15.00,
      outputPer1M: 75.00,
    },
    {
      id: 'gpt-4o',
      name: 'GPT-4o',
      provider: 'OpenAI',
      inputPer1M: 2.50,
      outputPer1M: 10.00,
    },
    {
      id: 'gpt-4o-mini',
      name: 'GPT-4o mini',
      provider: 'OpenAI',
      inputPer1M: 0.15,
      outputPer1M: 0.60,
    },
    {
      id: 'o1-preview',
      name: 'o1-preview',
      provider: 'OpenAI',
      inputPer1M: 15.00,
      outputPer1M: 60.00,
    },
    {
      id: 'o1-mini',
      name: 'o1-mini',
      provider: 'OpenAI',
      inputPer1M: 1.10,
      outputPer1M: 4.40,
    },
    {
      id: 'o3-mini',
      name: 'o3-mini',
      provider: 'OpenAI',
      inputPer1M: 1.10,
      outputPer1M: 4.40,
    },
    {
      id: 'gemini/gemini-1.5-pro',
      name: 'Gemini 1.5 Pro',
      provider: 'Google',
      inputPer1M: 1.25,
      outputPer1M: 5.00,
    },
    {
      id: 'gemini/gemini-1.5-flash',
      name: 'Gemini 1.5 Flash',
      provider: 'Google',
      inputPer1M: 0.075,
      outputPer1M: 0.30,
    },
    {
      id: 'gemini/gemini-2.0-flash',
      name: 'Gemini 2.0 Flash',
      provider: 'Google',
      inputPer1M: 0.10,
      outputPer1M: 0.40,
    },
  ],
  lastUpdated: null,
  source: 'fallback',
};

export const DEFAULT_SETTINGS = {
  setupComplete: false,
  selectedMonitor: 0,
  overlayPosition: 'top-right',
  opacity: 90,
  peakHours: {
    enabled: false,
    start: '09:00',
    end: '18:00',
    days: [1, 2, 3, 4, 5],
  },
  visibleModels: null,
  notifications: true,
  refreshIntervalHours: 6,
};
